name: hackomatic
description: "A mobile app for friendly hacking - control your hacking tools efficiently"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  # flutter_bluetooth_serial: ^0.4.0  # Temporarily disabled due to namespace issue
  # Use flutter_bluetooth_plus instead when bluetooth is needed
  network_info_plus: ^5.0.3
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  file_picker: ^8.0.7
  path_provider: ^2.1.3
  device_info_plus: ^10.1.2
  system_info2: ^4.0.0
  wifi_scan: ^0.4.1
  geolocator: ^12.0.0
  camera: ^0.10.5+9
  process_run: ^0.14.2
  flutter_local_notifications: ^17.2.2
  url_launcher: ^6.3.0
  archive: ^3.6.1
  crypto: ^3.0.3
  logger: ^2.4.0
  sqflite: ^2.3.3+1
  uuid: ^4.4.2
  package_info_plus: ^8.0.2
  battery_plus: ^6.0.2
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/scripts/
